<!DOCTYPE html>
<html lang="fr">

<head>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css"/>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>

        #mapid {
            height: 380px;
            width: 680px;
        }

        /* déclaration pour les markers */
        .circle {
            box-sizing: border-box;
            width: 30px;
            height: 30px;
            border-radius: 50%;
            background-color: rgba(255, 255, 255, 0.3);
            box-shadow: 0 0 10px #888;
        }

        .circle-marker {
            box-sizing: border-box;
            width: 30px;
            height: 30px;
        }

        .circle-red {
            border: 5px solid #F00;
        }

        .circle-green {
            border: 5px solid #0A0;
        }

        .circle-animate {
            animation-name: show-hide;
            animation-duration: 1s;
            animation-iteration-count: infinite;
            transform: scale(1);
        }

        @keyframes show-hide {
            0% {
                transform: scale(1);
            }
            50% {
                transform: scale(.5);
            }
            100% {
                transform: scale(1);
            }
        }

        #divBtnStart {
            margin: 0 auto;
            width: 100px;
        }

    </style>
    <title>TPFINAL</title>

</head>

<body>

<nav class="navbar navbar-light bg-light">
    <form class="form-inline">
        <input class="btn btn-outline-success" id="navConnect" type="button" value="connect" onclick="afficheConnect()">
        <input class="btn btn-sm btn-outline-secondary" id="navRegis" type="button" value="register">
    </form>
</nav>

<h2 id="AfficheName" style="display: none"></h2>

<div id="formulaireLogin">
    <div>
        <label for="Id">Id :</label>
        <input type="text" id="Id" name="user_Id">
    </div>
    <div>
        <label for="pwd">password :</label>
        <input type="password" id="pwd" name="user_pwd">
    </div>
    <input type="button" id="register" value="register">
    <input type="button" id="connect" value="connect">
</div>

<div id="formulaireRegis" style="display: none">
    <div>
        <label for="Id">Id :</label>
        <input type="text" id="IdRegis" name="user_Id" onblur="verifIdClient(this)"><label id="labelId"></label>
    </div>
    <div>
        <label for="pwd">password :</label>
        <input type="password" id="pwdRegis" name="user_pwd" oninput="verifPwdClient(this)"><label
                id="labelPwd"></label>
    </div>
    <input type="button" id="register2" value="register">
</div>

<div>
    <table id="idParties">

    </table>
</div>

<div id="divBtnStart" style="display: none">
    <button id="btnStart">start</button>
</div>
<br>
<div id="divScore" style="display: none">
    <p style="float: left;">Score :</p>
    <p id="score" style="float: left"></p>
    <form name="f_chrono">
        <input type="button" name="btn_dem" id="btn_dem" value="Démarrer"
               onclick="IndiquerMinutes(); DemarrerChrono();"/>
        <input type="button" name="btn_stop" id="btn_stop" value="Arreter !" onclick="ArreterChrono();"
               style="display: none;"/>
        <input type="button" name="btn_pause" id="btn_pause" value="Pause" onclick="PauseChrono();"
               style="display: none;"/>
    </form>
    <p id="chrono"></p>
</div>
<br>

<br>
<div>
    <section id="imgs" style="float: left; width: 380px"></section>
    <div id="mapid" style="float: left; display: none"></div>
</div>

<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">

    var tabPictures = [
        ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/2014-09-15_16-14-55_lion-belfort.jpg/390px-2014-09-15_16-14-55_lion-belfort.jpg"],
        ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Lagaredebelfortcentre.jpg/420px-Lagaredebelfortcentre.jpg"],
        ["http://www.ac-besancon.fr/local/cache-vignettes/L300xH182/batiment-iut-90credit_photoccludovicgodard-ufc-a680b.jpg?1547717515"],
        ["https://upload.wikimedia.org/wikipedia/fr/thumb/8/85/Gare_de_Belfort-Montb%C3%A9liard_TGV.jpg/420px-Gare_de_Belfort-Montb%C3%A9liard_TGV.jpg"],
        ["https://cdn-s-www.estrepublicain.fr/images/792C8934-2418-40B9-8B48-C34D1488B4B1/LER_22/le-bowling-a-six-pistes-illuminees-de-leds-fait-la-fierte-des-proprietaires-du-complexe-photos-xavier-gorau-1456149615.jpg"],
        ["https://laplacedufitness.com/wp-content/uploads/basic-fit-belfort.jpg"],
        ["https://photos.leclercdrive.fr/photo/leclerc-traiteur-belfort/magasin.ashx?idunivers=4&idmarque=2&idmagasin=019061"],
        ["https://www.belfort.fr/fileadmin/Minisites/sport/equipements/stades/stade_3_chenes.jpg"],
        ["https://static4.pagesjaunes.fr/media/ugc/base_nautique_et_de_loisirs_du_lac_du_malsaucy_09009300_065754622"],
        ["https://i.pinimg.com/originals/c9/7f/22/c97f22f28a6e40936e2be3329d0fa0eb.jpg"]
    ];

    var NomTabPictures = [
        ["Lion de Belfort"],
        ["Gare de Belfort"],
        ["IUT Belfort"],
        ["Gare TGV"],
        ["Bowling de Belfort"],
        ["Basic Fit Belfort"],
        ["Leclerc Belfort"],
        ["Stade des 3 Chênes"],
        ["Base de loisir du Lac du Malsaucy"],
        ["BU de Belfort"]
    ];

    var coordonneesPictures = [
        [47.636673, 6.864578],
        [47.633557, 6.853795],
        [47.643793, 6.840663],
        [47.585905, 6.897526],
        [47.638979, 6.855125],
        [47.64195, 6.858065],
        [47.627888, 6.862636],
        [47.647306, 6.844933],
        [47.684531, 6.808305],
        [47.640045, 6.856992]
    ];

    var mymap = L.map('mapid').setView([47.6333, 6.8667], 13);

    var latClick = null;
    var longClick = null;

    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(mymap);

    mymap.on('click', onMapClick);
    // fonction affichant un marker lors du clic sur un point de la carte. mofication de l'affichage de la souris


    var oIconRed = L.divIcon({
        iconAnchor: [15, 15],
        className: 'circle-marker',
        html: '<div class="circle-animate circle circle-red"></div>'
    });

    var oMarkerGreen = L.marker([0, 0], {icon: oIconRed});

    function onMapClick(e) {
        oMarkerGreen.setLatLng([e.latlng.lat, e.latlng.lng]).addTo(this);
        console.log("latitude : " + e.latlng.lat);
        console.log("longitude : " + e.latlng.lng);
        latClick = e.latlng.lat;
        longClick = e.latlng.lng;
        if (testDistance(coordonneesPictures[indexImage][0], coordonneesPictures[indexImage][1], 50)) {
            indexImage += 1;
            if (indexImage < tabPictures.length) {
                lanceJeu();
            } else {
                finJeu();
            }
        }
    }


    // for (let i = 0; i < tabPictures.length; i++) {
    //     $('#imgs').append('<div id=maDiv class=card> <img src=' + tabPictures[i] + ' width="360" height="240" alt="The Best for 2019 !!" ></div>');
    // }

    function lanceChrono() {
        console.log("start");
        IndiquerMinutes();
        DemarrerChrono();
    }

    // document.getElementById("imgs").innerHTML = '<div id=maDiv class=card> <img src=' + tabPictures[indexImg] + ' width="360" height="240" ></div>';

    var indexImage = 0;
    var score = 0;

    function lanceJeu() {
        var sortie = false;
        // document.getElementById("divBtnStart").style.display = "block";
        document.getElementById("divScore").style.display = "block";
        document.getElementById("mapid").style.display = "block";
        document.getElementById("score").innerText = score;
        if (indexImage < tabPictures.length) {
            document.getElementById("imgs").innerHTML = '<div id=maDiv class=card> <img src=' + tabPictures[indexImage] + ' width="360" height="240" ></div>';
        }
    }

    function finJeu() {
        console.log(score);
    }

    function testDistance(lat, long, d) {
        console.log("lat lng img : " + lat + ", " + long);
        console.log("lat lng click : " + latClick + ", " + longClick);
        var res = Distance(lat, long, latClick, longClick);
        if ((res < d) && (latClick !== null && longClick !== null)) {
            score += 5;
        }
        document.getElementById("score").innerText = score;
        return true;
    }

    function convertRad(input) {
        return (Math.PI * input) / 180;
    }

    function Distance(lat_a_degre, lon_a_degre, lat_b_degre, lon_b_degre) {

        R = 6378000; //Rayon de la terre en mètre

        lat_a = convertRad(lat_a_degre);
        lon_a = convertRad(lon_a_degre);
        lat_b = convertRad(lat_b_degre);
        lon_b = convertRad(lon_b_degre);

        d = R * (Math.PI / 2 - Math.asin(Math.sin(lat_b) * Math.sin(lat_a) + Math.cos(lon_b - lon_a) * Math.cos(lat_b) * Math.cos(lat_a)));
        return d;
    }


    $('#btnStart').click(function () {
        $.post("/game/add", {"id": nbId+1, "token": token, "enCours": 1, "NumPhoto":indexImage, "time":secondes, "Score":score, "idPlayer":idClient}).done(function () {
            idPartie=nbId+1;
            lanceChrono();
            lanceJeu();
            document.getElementById("idParties").style.display = "none";
            document.getElementById("btnStart").style.display = "none";
        }).fail(function (error) {
            alert(error);
        });

    });

    var idPartie;

    $('#btn_stop').click(function () {
        $.post("/game/update", {"id": idPartie, "token": token, "enCours": 1, "NumPhoto":indexImage, "time":secondes, "Score":score, "idPlayer":idClient}).done(function () {
            $.get("/game/id=" + idClient).done(function (result) {
                console.log(result["requete"]);
                nbId = result["requete"].length;
                document.getElementById("imgs").style.display = "none";
                document.getElementById("mapid").style.display = "none";
                document.getElementById("divScore").style.display = "none";
                affichePartie(result["requete"]);
                document.getElementById("idParties").style.display = "block";
                // document.getElementById("formulaireLogin").style.display = "none";
                document.getElementById("AfficheName").innerHTML = "Hello " + idClient;
                document.getElementById("AfficheName").style.display = "block";
                document.getElementById("divBtnStart").style.display = "block";

            }).fail(function (error) {
                alert(error);
            })
        }).fail(function (error) {
            alert(error);
        });
    });

    function afficheDisconnect() {
        if (document.getElementById("AfficheName").value !== null) {
            document.getElementById("navConnect").value = "disconnect";
        }
    }

    function affichePartie(tab) {
        document.getElementById("idParties").innerHTML = "";
        for (let i = 0; i < tab.length; i++) {
            if (tab[i]["enCours"] == 1) {
                document.getElementById("idParties").innerHTML = document.getElementById("idParties").innerHTML + "<tr> <td> id : " + tab[i]["id"] + " </td> <td> token : " + tab[i]["token"] + " </td> <td> en cours : oui </td> <td> Derniere photo : " + tab[i]["NumPhoto"] + " </td> <td> temps écoulé : " + tab[i]["time"] + " </td> <td> Score : " + tab[i]["Score"] + " </td> <td> <a id=\"id\" onclick=\"reprendrePartie(" + tab[i]["id"] + ")\">rependre partie</a> </td> </tr><br>";
            } else {
                document.getElementById("idParties").innerHTML = document.getElementById("idParties").innerHTML + "<tr> <td> id : " + tab[i]["id"] + " </td> <td> token : " + tab[i]["token"] + " </td> <td> en cours : non </td> <td> Derniere photo : " + tab[i]["NumPhoto"] + " </td> <td> temps écoulé : " + tab[i]["time"] + " </td> <td> Score : " + tab[i]["Score"] + " </td></tr><br>";
            }
        }
    }

    function reprendrePartie(id) {
        console.log(id);
    }

    function afficheConnect() {
        document.getElementById("navConnect").value = "connect";
        document.getElementById("AfficheName").innerHTML = "";
    }

    var resultTokenLogin = false;
    var token = "";
    var idClient;
    var idPlayer;
    var NumPhoto;
    var nbId;

    $(function () {
        $.get("/getToken").done(function (result) {
            // token = JSON.parse(result);
            token = result["token"];

            console.log(token);
        });

        $('#connect').click(function () {
            idClient = document.getElementById("Id").value;
            var pwdClient = document.getElementById("pwd").value;
            console.log(idClient);
            console.log(token);

            $.post("/login", {"id": idClient, "pwd": pwdClient, "token": token}).done(function (result) {
                // console.log(result["res"]);
                resultTokenLogin = result["res"];
                console.log("test res");
                console.log(resultTokenLogin);

                if (resultTokenLogin) {
                    $.get("/game/id=" + idClient).done(function (result2) {
                        // console.log(result2["requete"]);
                        nbId = result2["requete"].length;
                        affichePartie(result2["requete"]);
                        document.getElementById("formulaireLogin").style.display = "none";
                        document.getElementById("AfficheName").innerHTML = "Hello " + idClient;
                        document.getElementById("AfficheName").style.display = "block";
                        document.getElementById("divBtnStart").style.display = "block";
                    }).fail(function (error) {
                        alert(error);
                    })
                    // affichePartie();
                    // lanceJeu();
                    //
                    // console.log(picture[0]['items'][0]['description']);
                    //
                    // afficheDisconnect();
                }
            }).fail(function (error) {
                alert(error);
            });

        });

        $('#register').click(function () {
            document.getElementById("formulaireLogin").style.display = "none";
            document.getElementById("formulaireRegis").style.display = "block";
            document.getElementById("news").style.display = "none";
        });

        $('#register2').click(function () {
            var idClient = document.getElementById("IdRegis").value;
            var pwdClient = document.getElementById("pwdRegis").value;

            console.log(idClient);
            console.log(pwdClient);

            if (idClient.length < 2 && pwdClient.length < 8) {

            } else {
                $.post("/register", {"id": idClient, "pwd": pwdClient}).done(function (result) {
                    var resultRegis = result["res"];
                    console.log(resultRegis);
                    if (resultRegis) {
                        document.getElementById("formulaireRegis").style.display = "none";
                        document.getElementById("AfficheName").innerHTML = "Hello " + idClient;
                        document.getElementById("AfficheName").style.display = "block";
                        afficheImages();
                        afficheDisconnect();
                    } else {
                        alert("id deja utilisé");
                    }
                });
            }
        });

        $('#navConnect').click(function () {
            document.getElementById("formulaireLogin").style.display = "block";
            document.getElementById("formulaireRegis").style.display = "none";
            document.getElementById("news").style.display = "none";
        });

        $('#navRegis').click(function () {
            document.getElementById("formulaireLogin").style.display = "none";
            document.getElementById("formulaireRegis").style.display = "block";
            document.getElementById("news").style.display = "none";
        });

    });


    var secondes = 0;
    var timer;
    var pause = false;
    var text = "";
    var temps = 0;

    function IndiquerMinutes() {
        temps = 10 * 60;
    }

    function Chrono() {
        if (secondes < temps) {
            var minutes = Math.floor(secondes / 60);
            var heures = Math.floor(minutes / 60);
            secondes -= minutes * 60;
            if (heures > 0) {
                minutes -= heures * 60;
                if (minutes > 0) {
                    text = "Temps écoulé : " + heures + ' h ' + minutes + ' min ' + secondes + ' sec';
                } else {
                    text = "Temps écoulé : " + heures + ' h ' + secondes + ' sec';
                }
                minutes = minutes + (heures * 60);
                secondes = secondes + (minutes * 60) + 1;

            } else if (minutes > 0) {
                text = "Temps écoulé : " + minutes + ' min ' + secondes + ' sec';
                secondes = secondes + (minutes * 60) + 1;
            } else {
                text = "Temps écoulé : " + secondes + ' sec';
                secondes = secondes + (minutes * 60) + 1;
            }
        } else {
            clearInterval(timer);
            text = "Le temps est écoulé";
        }
        document.getElementById('chrono').innerHTML = text;
    }

    function DemarrerChrono() {
        timer = setInterval('Chrono()', 1000);
        document.getElementById('btn_dem').style.display = 'none';
        document.getElementById('btn_stop').style.display = 'inline';
        document.getElementById('btn_pause').style.display = 'inline';

    }

    function ArreterChrono() {
        clearInterval(timer);
        document.getElementById('btn_dem').style.display = 'inline';
        document.getElementById('btn_stop').style.display = 'none';
        document.getElementById('btn_pause').style.display = 'none';
    }

    function PauseChrono() {
        if (!pause) {
            pause = true;
            clearInterval(timer);
            text = '[EN PAUSE] ' + text;
            document.getElementById('chrono').innerHTML = text;
            document.getElementById('btn_stop').style.display = 'none';
            document.getElementById('btn_pause').value = 'Reprendre';
        } else {
            pause = false;
            DemarrerChrono();
            document.getElementById('btn_pause').value = 'Pause';
        }
    }


</script>

</body>

</html>